import React, { useState, useEffect } from "react";
import "./CreatePlaylist.css";

import axios from "axios";

import { Card } from "./../../containers";
import { Button } from "./../../components";
import api from "../../../api";

function CreatePlaylist() {
  const [playlistSession, setPlaylistSession] = useState(null);

  useEffect(() => {
    getSessionPlaylist();
  }, []);

  function getSessionPlaylist() {
    axios
      .get(api.playlistSession)
      .then(function (response) {
        console.log(response);
        setPlaylistSession(response.data);
      })
      .catch(function (error) {
        console.error(error);
      });
  }

  return (
    <div className="create-playlist">
      <Card className="create-playlist-card">
        <div className="create-playlist-header">
          <div className="create-playlist-header-picture">
            <img alt="playlist-profile" />
          </div>
          <div className="create-playlist-header-info">
            <input></input>
            <p>Playlist generated by user</p>
            <Button style={{ width: "200px" }} isPrimary={true}>
              Create Smart Playlist
            </Button>
          </div>
        </div>
        <div className="create-playlist-songs">
          <div className="create-playlist-song-labels format-column-grid">
            <div>Song</div>
            <div>Artist</div>
            <div>Album</div>
            <div>Length</div>
            <div></div>
          </div>
          {playlistSession !== null ? (
            playlistSession.tracks.length > 0 ? (
              <div>
                {playlistSession.tracks.map(function (song, index) {
                  return <div key={index}>hehe</div>;
                })}
              </div>
            ) : (
              <div className="create-playlist-no-songs">
                <p>No songs added to playlist</p>
              </div>
            )
          ) : null}
        </div>
      </Card>
    </div>
  );
}

export default CreatePlaylist;
